### PR TITLE
To Do List - Basic Structure

### PR DESCRIPTION
**Pull request by orozCoding**
In this first feature-branch, I created the basic structure for the To Do List App.

- Installed the webpack ✔️ 
- Created index.html ✔️ 
- Created index.js with main functions ✔️ 
- Created style.css with general style ✔️ 

🏁  At this point, the app is capable of sorting the array of tasks  based on their index number,  and render it into the task-list.

### CODE REVIEW

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Angel, 

Highlight:
- Good job on this project, it is working exactly as expected.

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] according to the requirements the node modules need to be added to the `.gitignore` right now it is making your repository very slow, have a look at [this article](https://medium.com/@buyananderson/accidentally-push-to-github-the-node-modules-without-ignoring-it-f766dad15eaa) if you need help removing it from your remote repo.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by orozCoding** [comment]
Thank you! I just removed and ignored the folder.

**Comment by orozCoding** [comment]
Thank you @mikethreels 

I just removed and ignored the folder.

✔️

**Review by elyor-doniyorov — APPROVED** [review]
Hi @orozCoding, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by orozCoding** [comment]
Thank you @elyor-doniyorov

**Pull request merged**
